-- 코드를 입력하세요
WITH SALE_INFO as (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)
SELECT PRODUCT_CODE, (p.PRICE * s.TOTAL_AMOUNT) as SALES
FROM PRODUCT p 
JOIN SALE_INFO s USING (PRODUCT_ID)
ORDER BY SALES desc, PRODUCT_CODE asc;
