-- 코드를 작성해주세요
WITH info as (
    SELECT FISH_TYPE, count(FISH_TYPE) as FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT i.FISH_COUNT, n.FISH_NAME
FROM FISH_NAME_INFO n
RIGHT JOIN info i ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY FISH_COUNT desc;