-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, 
        r.CONTENTS, LEFT(r.CREATED_DATE, 10)
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE like '2022-10%'
ORDER BY r.CREATED_DATE asc, b.TITLE asc;